"use client";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Cpu, Brain, Zap, Sparkles, Database } from "lucide-react";
import Link from "next/link";
import LoadingTerminal from "@/components/LoadingTerminal";

export default function SkillsPage() {
  const [skills, setSkills] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isCached, setIsCached] = useState(false);
  const [profile, setProfile] = useState(null);

  useEffect(() => {
    const savedProfile = localStorage.getItem("futureTwinProfile");
    if (savedProfile) {
      const p = JSON.parse(savedProfile);
      setProfile(p);
      
      const cacheKey = `skills_${p.name}_${p.age}`;
      const cachedData = localStorage.getItem(cacheKey);
      
      if (cachedData) {
        setSkills(JSON.parse(cachedData));
        setIsCached(true);
        setIsLoading(false);
      } else {
        generateSkills(p, cacheKey);
      }
    } else {
        setIsLoading(false);
    }
  }, []);

  const generateSkills = async (p, cacheKey) => {
    try {
      const res = await fetch("/api/skills", {
        method: "POST",
        body: JSON.stringify({ profile: p }),
      });
      const data = await res.json();
      if (data.skills) {
        setSkills(data.skills);
        localStorage.setItem(cacheKey, JSON.stringify(data.skills));
      }
    } catch (err) {
      console.error("Skills generation error", err);
    } finally {
      setIsLoading(false);
    }
  };

  const SkillCard = ({ skill, idx, colorClass }) => (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: idx * 0.1 }}
      className="glass group relative overflow-hidden rounded-3xl p-6 hover:border-white/20 transition-all font-sans"
    >
       <div className={`absolute top-0 left-0 h-1 w-full ${colorClass === 'primary' ? 'bg-primary' : colorClass === 'accent' ? 'bg-accent' : 'bg-secondary'}`} />
       <h4 className="text-lg font-bold text-white mb-2">{skill.name}</h4>
       <p className="text-sm text-white/50 leading-relaxed">{skill.description}</p>
    </motion.div>
  );

  if (isLoading) {
    return <LoadingTerminal message="Synthesizing Synaptic Pathways..." />;
  }

  return (
    <div className="min-h-screen py-20 px-4 md:px-8">
      <div className="mx-auto max-w-6xl">
        <header className="mb-16 flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center gap-2 text-white/50 transition-colors hover:text-white">
            <ArrowLeft className="h-5 w-5" />
            <span>Dashboard</span>
          </Link>
          <div className="text-right">
            <h1 className="neon-text text-3xl font-bold">Skill Synthesis</h1>
            <div className="flex items-center justify-end gap-2 text-[10px] uppercase tracking-widest mt-1">
              {isCached ? (
                <span className="flex items-center gap-1 text-primary">
                  <Database className="h-3 w-3" />
                  Skillmap Retrived from Local Memory
                </span>
              ) : (
                <span className="text-white/30 italic">Generated by Gemini Synapse Engine</span>
              )}
            </div>
          </div>
        </header>

        <div className="space-y-16">
          {/* Core Skills */}
          <section>
            <div className="mb-8 flex items-center gap-3">
              <div className="rounded-2xl bg-primary/10 p-3">
                <Cpu className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white uppercase tracking-tighter">Core Foundations</h2>
                <p className="text-sm text-white/40">Essential skills for your primary domain</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {skills?.coreSkills.map((s, i) => (
                <SkillCard key={i} skill={s} idx={i} colorClass="primary" />
              ))}
            </div>
          </section>

          {/* Emerging Skills */}
          <section>
            <div className="mb-8 flex items-center gap-3">
              <div className="rounded-2xl bg-accent/10 p-3">
                <Zap className="h-6 w-6 text-accent" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white uppercase tracking-tighter">Emerging Systems</h2>
                <p className="text-sm text-white/40">Next-gen capabilities for the 2030s</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {skills?.emergingSkills.map((s, i) => (
                <SkillCard key={i} skill={s} idx={i + 3} colorClass="accent" />
              ))}
            </div>
          </section>

          {/* Mindset Skills */}
          <section>
            <div className="mb-8 flex items-center gap-3">
              <div className="rounded-2xl bg-secondary/10 p-3">
                <Brain className="h-6 w-6 text-secondary" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white uppercase tracking-tighter">Mindset & Ethics</h2>
                <p className="text-sm text-white/40">Soft skills for a rapidly changing world</p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {skills?.mindsetSkills.map((s, i) => (
                <SkillCard key={i} skill={s} idx={i + 6} colorClass="secondary" />
              ))}
            </div>
          </section>
          
          <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="glass rounded-3xl p-10 text-center relative overflow-hidden"
          >
              <div className="absolute inset-0 bg-gradient-to-r from-primary/5 via-transparent to-secondary/5" />
              <Sparkles className="h-8 w-8 text-primary mx-auto mb-4" />
              <h3 className="text-xl font-bold text-white mb-2 underline decoration-primary/30 underline-offset-8">THE 2035 ADVANTAGE</h3>
              <p className="max-w-2xl mx-auto text-white/60 leading-relaxed italic">
                By focusing on these skills today, you are positioning yourself at the forefront of the upcoming technological and social shift. Your 2035 self is built on the foundations you lay now.
              </p>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
